channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - python=3.6
  - sos-pbs
  - sos
  - jupyterlab-sos
  - sos-papermill
  - sos-notebook
  - sos-r
  - sos-python
  - r-essentials
  - r-arrow
  - plotly
  - scipy

