channels:
  - defaults
  - conda-forge
  - plotly
  - r
dependencies:
  - python
  - sos
  - sos-notebook
  - sos-python
  - plotly
  - scipy
  - r-essentials
  - r-arrow
  - pyarrow
  - sos-r
  - pandas

